### ISSUE TITLE
Problem with tslint.json rules

### ISSUE THREAD

**Issue by osnoser1** [schuchard/prettier-schematic#11]
**Describe the bug**
Hi, from a time to here @angular/cli adds to tslint.json "tslint: recommended", because of this all the rules are not deleted.

**To Reproduce**
Create a new angular app with @angular/cli

**Expected behavior**
Maybe add tslint-config-prettier?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Windows 10 64 bits
 - Node Version [e.g. 22] 8.12.0
 - Angular & Angular/CLI Version 7.3.4

**Additional context**

**Comment by JsonPipe** [comment]
Yes if you set prettier to `singleQuote: true` the corresponding setting in `tslint.json` `"quotemark": [true, "single"],` shouldn't be removed, because it make **tslint** default to use double quotes and throw linting errors `should be "" and not ''` all over the codebase after running `npm run prettier`. Readding `"quotemark": [true, "single"],` fixed the problem.

**Comment by schuchard** [comment]
Thanks for reporting and debugging. The latest release (3.0.0) should resolve this issue as the schematic now relies on the `tslint-config-prettier` package from Prettier.
