### ISSUE TITLE
Only CSS file suffix included by default, even though project uses preprocessor

### ISSUE THREAD

**Issue by vmasek** [schuchard/prettier-schematic#19]
**Describe the bug**
`css` file suffix only is mentioned in the prettier npm script  

**To Reproduce**
Steps to reproduce the behaviour:
1. run this schematic on an Angular project using SASS/SCSS
2. open `package.json`
3. see the `prettier` script`

**Expected behaviour**
It should detect what is the project style preprocessor and use its file suffix along with CSS

**Desktop (please complete the following information):**
 - all Angular & Angular/CLI Versions

**Additional question**:
Why is there `component.html` alongside with `html`? It does not seem to have any additional effect.

**Comment by schuchard** [comment]
Hi @vmasek,

I agree that the `.scss` and `.less` extensions should be added. I've done that [here](https://github.com/schuchard/prettier-schematic/pull/20/files#diff-563284711374ed991e0b2444e2654fe8R189). However I don't know if that should be a "smart" decision since a project could change their style extension and globing files that don't exist doesn't appear to cause any issues. 

I believe the `component.html` glob is used to infer what parser to use. The `html` glob may be sufficient but for the sake of explicitness I'm leaving it there. From the [docs](https://prettier.io/blog/2018/11/07/1.15.0.html#automatic-parser-inference):


> Prettier uses filename to infer which parser to use. Here's the default patterns for HTML, Vue, and Angular:
>
> *.html: --parser html
> *.component.html: --parser angular
> *.vue: --parser vue
>
> Make sure your filename matches the correct parser (especially for Angular users); if it does not, you will have to manually specify which parser to use via the overrides field.
>
> Note that framework-specific formatting won't be triggered in --parser html.

**Comment by vmasek** [comment]
Thanks for the reply and explanation, I think it is good enough to have it explicitly stated rather than "smart"
